theme: jekyll-theme-primer
markdown: CommonMarkGhPages
title: "Obsei: A workflow automation tool for text analysis need"
description: "Obsei is intended to be a workflow automation tool for text analysis need"
